### ISSUE TITLE
Move compiler stage1 gaps

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#121]
Project view: https://github.com/orgs/solana-labs/projects/11/views/1

- [x] Primitive types (#47) 
- [x] Aggregate types
  - [x] Basic (concrete) structs (#25)
  - [x] Tuple (Vec<Type>) (#165)
  - [x] Generic structs (#171)
  - [x] ~~Abilities (partly or largely VM work).~~ (will happen in stage 2 or later).
- [x] Functions (#6)
  - [x] Basic (concrete) functions
  - [x] Generic functions (#60)
  - [x] Native functions
- [x] Build `move-stdlib` (each file as functionality comes online)
  - [x] ascii.move  
  - [x] bit_vector.move
  - [x] fixed_point32.move (#119)
  - [x] option.move (#185)
  - [x] string.move
  - [x] bcs.move   (_support in `move-native` library needed_)
  - [x] error.move
  - [x] hash.move
  - [x] signer.move (#157)
  - [x] type_name.move    (_support in `move-native` library needed_)
  - [x] vector.move (#173, #174)
- [x] Memory model (#122)
- [x] Builtins (#123)
- [x] Debugging (#124)
- [x] Event (#125)
- [ ] Testing (#70, #84, #85, #115)
  - [ ] Transaction bundle
  - [ ] List of requirements into a transaction bundle
